-- UniEvent Relational Database Schema
-- Target Platform: MySQL / MariaDB (XAMPP environment)

CREATE DATABASE IF NOT EXISTS unievent_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE unievent_db;

-- --------------------------------------------------------
-- Table structure for table `students`
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS students (
    student_id VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('student', 'leader', 'admin') DEFAULT 'student',
    faculty VARCHAR(100) DEFAULT NULL,
    department VARCHAR(100) DEFAULT NULL,
    avatar VARCHAR(255) DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (student_id),
    UNIQUE KEY uk_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Table structure for table `event`
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS event (
    event_id VARCHAR(50) NOT NULL,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    location VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    image_url VARCHAR(255) DEFAULT NULL,
    created_by VARCHAR(50) NOT NULL, -- Serves as submitted_by
    approved_by VARCHAR(50) DEFAULT NULL,
    status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
    club_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (event_id),
    CONSTRAINT fk_event_created_by FOREIGN KEY (created_by) REFERENCES students (student_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_event_approved_by FOREIGN KEY (approved_by) REFERENCES students (student_id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Table structure for table `sessions`
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS sessions (
    session_id VARCHAR(100) NOT NULL,
    student_id VARCHAR(50) NOT NULL,
    login_token VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (session_id),
    CONSTRAINT fk_sessions_student FOREIGN KEY (student_id) REFERENCES students (student_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Table structure for table `registrations`
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS registrations (
    registration_id INT AUTO_INCREMENT NOT NULL,
    student_id VARCHAR(50) NOT NULL,
    event_id VARCHAR(50) NOT NULL,
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (registration_id),
    UNIQUE KEY uk_student_event (student_id, event_id),
    CONSTRAINT fk_registrations_student FOREIGN KEY (student_id) REFERENCES students (student_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_registrations_event FOREIGN KEY (event_id) REFERENCES event (event_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Seed Initial Data
-- --------------------------------------------------------

-- Insert Default Users (all default passwords are: password123)
-- Hash generated by PHP: $2y$10$i9ILhdAqobmvKcxVFVHoLeDPqzgQt1SaflvjT2q0iMo9u9QhtJ5he
INSERT INTO students (student_id, name, email, password_hash, role, faculty, department) 
VALUES 
('ST-2024-001', 'Alex Mercer', 'student@unievent.com', '$2y$10$i9ILhdAqobmvKcxVFVHoLeDPqzgQt1SaflvjT2q0iMo9u9QhtJ5he', 'student', 'Engineering', 'Computer Science'),
('FA-2021-042', 'Dr. Sarah Connor', 'leader@unievent.com', '$2y$10$i9ILhdAqobmvKcxVFVHoLeDPqzgQt1SaflvjT2q0iMo9u9QhtJ5he', 'leader', 'Science', 'Mathematics'),
('AD-2020-001', 'Admin User', 'admin@unievent.com', '$2y$10$i9ILhdAqobmvKcxVFVHoLeDPqzgQt1SaflvjT2q0iMo9u9QhtJ5he', 'admin', 'Administration', 'Operations')
ON DUPLICATE KEY UPDATE student_id=student_id;

-- Insert Default Events
INSERT INTO event (event_id, title, description, date, time, location, category, image_url, created_by, club_name)
VALUES
('evt-1', 'UniHack 2026', 'A 24-hour hackathon where students build prototypes to solve real-world problems. Great prizes and food are provided!', '2026-06-25', '09:00:00', 'Campus Innovation Hub', 'Academic', 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=60', 'AD-2020-001', 'Coding Club'),
('evt-2', 'Spring Jam Concert', 'A musical night featuring live student bands, art displays, food trucks, and absolute fun under the stars.', '2026-06-30', '18:00:00', 'Open Air Theater', 'Cultural', 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=60', 'AD-2020-001', 'Music & Arts Society'),
('evt-3', 'Annual Athletics Meet', 'Watch or compete in the ultimate showcase of speed, endurance, and strength. Registrations open for all athletes.', '2026-07-05', '08:00:00', 'University Sports Stadium', 'Athletics', 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=800&auto=format&fit=crop&q=60', 'AD-2020-001', 'Sports Varsity Club'),
('evt-4', 'Debate Finals 2026', 'The grand finale of the inter-faculty championship. Witness students debate critical issues about AI and ethics.', '2026-06-18', '14:30:00', 'Main Auditorium', 'Academic', 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&auto=format&fit=crop&q=60', 'AD-2020-001', 'Debating Society')
ON DUPLICATE KEY UPDATE event_id=event_id;

-- Insert Default Registration for Alex Mercer (ST-2024-001) to UniHack 2026 (evt-1)
INSERT INTO registrations (student_id, event_id, registered_at)
VALUES
('ST-2024-001', 'evt-1', '2026-05-12 14:35:00')
ON DUPLICATE KEY UPDATE student_id=student_id;
